site_dir: '../notebookjp.github.io'

# Project information
site_name: ゲーム開発のためのノート PC 選び | notebookjp
site_url: https://notebookjp.github.io/
site_author: Ryo Suzuki
site_description: ゲーム開発のためのノート PC

# Repository
repo_name: Reputeless/Laptops
repo_url: https://github.com/Reputeless/Laptops
edit_uri: ""

# Theme
theme:
  name: material
  language: ja
  palette:
    primary: pink
    accent: pink
  logo: assets/images/laptop-white-48dp.svg
  favicon: assets/images/logo.png
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  plugins:
  - search:
      lang:
        - ja
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Reputeless
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 2
      slugify: !!python/name:pymdownx.slugs.uslugify
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - notebookjp_styles.css

# Page tree
nav:
  - 最新データ: index.md
  - 過去のデータ:
    - 2023 年 4 月: archive/2023-04-19.md
    - 2022 年 9 月: archive/2022-09-19.md
    - 2022 年 5 月: archive/2022-05-31.md
    - 2022 年 3 月: archive/2022-03-26.md
    - 2022 年 1 月: archive/2022-01-22.md
    - 2021 年 11 月: archive/2021-11-17.md
    - 2021 年 9 月: archive/2021-09-05.md
    - 2021 年 6 月: archive/2021-06-16.md
    - 2021 年 5 月: archive/2021-05-07.md
    - 2021 年 3 月: archive/2021-03-16.md
    - 2021 年 2 月: archive/2021-02-11.md
    - 2021 年 1 月: archive/2021-01-26.md
    - 2020 年 12 月: archive/2020-12-15.md
    - 2020 年 11 月: archive/2020-11-13.md
    - 2020 年 10 月: archive/2020-10-15.md
    - 2020 年 9 月: archive/2020-09-11.md
    - 2020 年 8 月: archive/2020-08-07.md
    - 2020 年 7 月: archive/2020-07-07.md
    - 2020 年 5 月: archive/2020-05-27.md
    - 2020 年 4 月: archive/2020-04-26.md
    - 2020 年 2 月: archive/2020-02-04.md
    - 2019 年 12 月: archive/2019-12-26.md
    - 2019 年 11 月: archive/2019-11-07.md
    - 2019 年 10 月: archive/2019-10-01.md
    - 2019 年 9 月: archive/2019-09-20.md
  - 学割:
    - 学割の使用: student/gakuwari.md
